USE DB_IMOVEIS
GO

CREATE PROCEDURE PREENCHE_TABELA_DB_IMOVEIS (@TABELA VARCHAR(100), @QTD_REGISTROS INT)
AS
BEGIN
	DECLARE 
		@CONT INT = 0

		EXEC RETORNA_ULTIMO_REGISTRO @TABELA, @QTD_REGISTROS , @CONT, @QTD_REGISTROS OUT, @CONT OUT

	IF(@TABELA = 'ESTADO')
	BEGIN
		IF ((SELECT COUNT(*) FROM ESTADO) <> 27 AND EXISTS (SELECT * FROM SYS.all_objects WHERE NAME = 'ESTADO'))
		BEGIN 
			DELETE FROM ESTADO 
			INSERT INTO ESTADO VALUES ('AC','Acre'),('AL','Alagoas'),('AM','Amazonas'),('AP','Amapá'),('BA','Bahia'),('CE','Ceará'),('DF','Distrito Federal'),('ES','Espírito Santo'),('GO','Goiás'),('MA','Maranhão'),('MG','Minas Gerais'),('MS','Mato Grosso do Sul'),('MT','Mato Grosso'),('PA','Pará'),('PB','Paraíba'),('PE','Pernambuco'),('PI','Piauí'),('PR','Paraná'),('RJ','Rio de Janeiro'),('RN','Rio Grande do Norte'),('RO','Rondônia'),('RR','Roraima'),('RS','Rio Grande do Sul'),('SC','Santa Catarina'),('SE','Sergipe'),('SP','São Paulo'),('TO','Tocantins')
			PRINT 'TABELA ESTADO PREENCHIDA'
		END
		ELSE
		BEGIN
			PRINT 'TABELA COMPLETA OU INEXISTENTE'
		END
	END

	IF(@TABELA = 'CIDADE')
	BEGIN

		DECLARE 
			@NOME_CIDADE VARCHAR(MAX) = '',
			@NUM_SG_ESTADO INT = 0,
			@ESTADO CHAR(2) = ''
		

		WHILE @CONT < @QTD_REGISTROS
		BEGIN
	
			SET @NOME_CIDADE   = 'NM_CIDADE' + CONVERT(VARCHAR(MAX), @CONT)
			SET @NUM_SG_ESTADO = dbo.NUMERO_ALEATORIO(1,27, RAND())
			SET @ESTADO        = dbo.SELECIONA_ESTADO(@NUM_SG_ESTADO)
	
		
			INSERT INTO CIDADE VALUES (@CONT, @NOME_CIDADE, @ESTADO)
	
			SET @CONT = @CONT + 1  
		END

	END


	IF(@TABELA = 'BAIRRO')
	BEGIN

		WHILE @CONT < @QTD_REGISTROS
		BEGIN
		
			DECLARE 
				@NOME_BAIRRO VARCHAR(MAX),
				@CD_CIDADE  INT,
				@SG_ESTADO CHAR(2)

			SET @NOME_BAIRRO = 'NM_BAIRRO' + CONVERT(VARCHAR(MAX), @CONT)
			SET @CD_CIDADE = dbo.SELECIONA_CIDADE(RAND())
			SET @SG_ESTADO = (SELECT SG_ESTADO FROM CIDADE WHERE CD_CIDADE = @CD_CIDADE)


			INSERT INTO BAIRRO VALUES (@CONT,@NOME_BAIRRO, @CD_CIDADE, @SG_ESTADO)
		
					
			SET @CONT = @CONT + 1 
		END

	END


	IF (@TABELA = 'COMPRADORES')
	BEGIN


		DECLARE 
			@NM_COMPRADOR VARCHAR(MAX),
			@NR_CPF_COMPRADOR VARCHAR(11),
			@CD_CIDADE_COMPRADOR INT,
			@CD_BAIRRO_COMPRADOR INT,
			@SG_ESTADO_COMPRADOR CHAR(2),
			@TEL_COMPRADOR VARCHAR(9),
			@NM_ENDERECO_COMPRADOR VARCHAR(400)

		WHILE @CONT <= @QTD_REGISTROS
		BEGIN
			-- SETA OS PARÂMETROS PARA O INSERT 
	
				SET @NM_COMPRADOR = 'NM_COMPRADOR' + CONVERT(VARCHAR(MAX), @CONT)
				SET @NR_CPF_COMPRADOR = CONVERT(VARCHAR(11),dbo.NUMERO_ALEATORIO(11111111111,99999999999, RAND()))
				SET @CD_BAIRRO_COMPRADOR = dbo.SELECIONA_BAIRRO(RAND())

				SELECT 
					@CD_CIDADE_COMPRADOR = CD_CIDADE,
					@SG_ESTADO_COMPRADOR = SG_ESTADO
				FROM BAIRRO 
				WHERE CD_BAIRRO = @CD_BAIRRO_COMPRADOR

				SET @TEL_COMPRADOR = dbo.NUMERO_ALEATORIO(111111111,999999999, RAND())
				SET @NM_ENDERECO_COMPRADOR = 'NM_ENDERECO_COMPRADOR' + CONVERT(VARCHAR(MAX), @CONT)

		

			INSERT INTO COMPRADORES VALUES (@CONT, @NM_COMPRADOR, @NM_ENDERECO_COMPRADOR, @NR_CPF_COMPRADOR, @CD_CIDADE_COMPRADOR, @CD_BAIRRO_COMPRADOR, @SG_ESTADO_COMPRADOR, @TEL_COMPRADOR)
	
			SET @CONT = @CONT + 1

		END
	END



	IF(@TABELA = 'VENDEDOR')
	BEGIN

		WHILE @CONT <= @QTD_REGISTROS
		BEGIN
		
			DECLARE 
				@NM_VENDEDOR          VARCHAR(MAX)  = 'NM_VENDEDOR' + CONVERT(VARCHAR(MAX), @CONT),
				@NM_ENDERECO_VENDEDOR VARCHAR(MAX)  = 'NM_ENDERECO_VENDEDOR' + CONVERT(VARCHAR(MAX), @CONT),
				@NR_CPF_VENDEDOR      VARCHAR(12)   = dbo.NUMERO_ALEATORIO(11111111111, 999999999999, RAND()),
				@CD_BAIRRO_VENDEDOR   INT           = dbo.SELECIONA_BAIRRO(RAND()),
				@CD_CIDADE_VENDEDOR   INT,
				@SG_ESTADO_VENDEDOR   CHAR(2),
				@TEL_VENDEDOR         INT           = dbo.NUMERO_ALEATORIO(111111111, 999999999,RAND()),
				@DATA_NASC_VENDEDOR   SMALLDATETIME = dbo.GERA_DATA_ALEATORIA(RAND())

			SELECT 
				@CD_CIDADE_VENDEDOR = CD_CIDADE,
				@SG_ESTADO_VENDEDOR = SG_ESTADO
			FROM BAIRRO
			WHERE CD_BAIRRO = @CD_BAIRRO_VENDEDOR

			INSERT INTO VENDEDOR VALUES (@CONT, @NM_VENDEDOR, @NM_ENDERECO_VENDEDOR, @NR_CPF_VENDEDOR, @CD_CIDADE_VENDEDOR, @CD_BAIRRO_VENDEDOR,@SG_ESTADO_VENDEDOR,@TEL_VENDEDOR,@DATA_NASC_VENDEDOR)

			SET @CONT = @CONT + 1 
		END
	END

	IF(@TABELA = 'IMOVEL')
	BEGIN 


		WHILE (@CONT <= @QTD_REGISTROS)
		BEGIN 

			DECLARE 
				@CD_VENDEDOR_IMOVEL INT = dbo.SELECIONA_VENDEDOR(RAND()),
				@CD_CIDADE_VENDEDOR_IMOVEL INT,
				@CD_BAIRRO_VENDEDOR_IMOVEL INT,
				@SG_SIGLA_ESTADO_VENDEDOR_IMOVEL CHAR(2),
				@NM_ENDERECO_VENDEDOR_IMOVEL VARCHAR(200),
				@NR_AREA_TOTAL DECIMAL, 
				@VL_PRECO DECIMAL,
				@DATA_LANCTO SMALLDATETIME

			SELECT 
				@CD_CIDADE_VENDEDOR_IMOVEL = CD_CIDADE,
				@SG_SIGLA_ESTADO_VENDEDOR_IMOVEL = SG_ESTADO
			FROM VENDEDOR
			WHERE CD_VENDEDOR = @CD_VENDEDOR_IMOVEL


			--- SELECIONA O BAIRRO PELA CIDADE DO VENDEDOR


			SET @CD_BAIRRO_VENDEDOR_IMOVEL = dbo.SELECIONA_BAIRRO_POR_CIDADE(@CD_CIDADE_VENDEDOR_IMOVEL, RAND())
		
			SET @NM_ENDERECO_VENDEDOR_IMOVEL = 'NM_ENDERECO_VENDEDOR_IMOVEL' + CONVERT(VARCHAR(MAX), @CONT)

			SET @NR_AREA_TOTAL = dbo.NUMERO_ALEATORIO(50, 1000, RAND())

			SET @VL_PRECO = dbo.NUMERO_ALEATORIO(25000,500000, RAND())

			SET @DATA_LANCTO = dbo.GERA_DATA_ALEATORIA(RAND())
			----------------------------------------------


			INSERT INTO IMOVEL VALUES (@CONT,@CD_VENDEDOR_IMOVEL,@CD_BAIRRO_VENDEDOR_IMOVEL,@CD_CIDADE_VENDEDOR_IMOVEL,@SG_SIGLA_ESTADO_VENDEDOR_IMOVEL,@NM_ENDERECO_VENDEDOR_IMOVEL, NULL, @NR_AREA_TOTAL, @VL_PRECO, NULL, 0,@DATA_LANCTO)

			SET @CONT = @CONT + 1
		END
	END

	IF(@TABELA = 'OFERTA')
	BEGIN 


		DECLARE 
			@CD_IMOVEL_OFERTA    INT,
			@CD_COMPRADOR_OFERTA INT,
			@VL_OFERTA           DECIMAL,
			@PRECO_IMOVEL        DECIMAL, 
			@DT_OFERTA           SMALLDATETIME

		WHILE @CONT <= @QTD_REGISTROS
		BEGIN

		SET @CD_IMOVEL_OFERTA = dbo.SELECIONA_IMOVEL(RAND())

		SET @CD_COMPRADOR_OFERTA = dbo.SELECIONA_COMPRADORES(RAND())

		SET @DT_OFERTA = CONVERT(SMALLDATETIME, GETDATE())

		--- OFERTA DEVE SER MAIOR QUE O VALOR DO IMOVEL

		SELECT 
			@VL_OFERTA = dbo.NUMERO_ALEATORIO(VL_PRECO, (VL_PRECO + (VL_PRECO * 0.5)), RAND())
		FROM IMOVEL 
		WHERE CD_IMOVEL = @CD_IMOVEL_OFERTA

		INSERT INTO OFERTA VALUES (@CONT, @CD_IMOVEL_OFERTA, @CD_COMPRADOR_OFERTA, @VL_OFERTA, @DT_OFERTA)

		--- REGISTRA OFERTA NO IMOVEL
			EXEC REGISTRA_OFERTA_IMOVEL @CD_IMOVEL_OFERTA ,@CONT  
		-----------------------------

		SET @CONT = @CONT + 1 
		END
	END
END
GO